package no.nav.helse.bakrommet

enum class BeregningskoderDekningsgrad {
    ARBEIDSTAKER_DEKNINGSGRAD_100,
    ORDINAER_SELVSTENDIG_DEKNINGSGRAD_80,
    ORDINAER_SELVSTENDIG_NAVFORSIKRING_DEKNINGSGRAD_100,
    SELVSTENDIG_KOLLEKTIVFORSIKRING_DEKNINGSGRAD_100,
    FRILANSER_DEKNINGSGRAD_100,
    INAKTIV_DEKNINGSGRAD_65,
    INAKTIV_DEKNINGSGRAD_100,
    DAGPENGEMOTTAKER_DEKNINGSGRAD_100,
}

enum class BeregningskoderSykepengrunnlag {
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_SKJOENN_AVVIK,
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_SKJOENN_URIKTIG,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_SKJOENN_VARIG_ENDRING,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_SKJOENN_NYIARB,
    TODO_TRENGER_NY_VERDI,
}
