package no.nav.helse.bakrommet

enum class BeregningskoderDekningsgrad {
    ARBEIDSTAKER_DEKNINGSGRAD_100,
    ORDINAER_SELVSTENDIG_DEKNINGSGRAD_80,
    ORDINAER_SELVSTENDIG_NAVFORSIKRING_DEKNINGSGRAD_100,
    SELVSTENDIG_KOLLEKTIVFORSIKRING_DEKNINGSGRAD_100,
    FRILANSER_DEKNINGSGRAD_100,
    INAKTIV_DEKNINGSGRAD_65,
    INAKTIV_DEKNINGSGRAD_100,
    DAGPENGEMOTTAKER_DEKNINGSGRAD_100,
}

enum class BeregningskoderSykepengrunnlag
