package no.nav.helse.bakrommet

enum class BeregningskoderDekningsgrad {
    ARBEIDSTAKER_DEKNINGSGRAD_100,
    SELVSTENDIG_DEKNINGSGRAD_80,
    SELVSTENDIG_NAVFORSIKRING_DEKNINGSGRAD_100,
    SELVSTENDIG_KOLLEKTIVFORSIKRING_DEKNINGSGRAD_100,
    FRILANSER_DEKNINGSGRAD_100,
    INAKTIV_DEKNINGSGRAD_65,
    INAKTIV_DEKNINGSGRAD_100,
    ARBEIDSLEDIG_DEKNINGSGRAD_100,
}

enum class BeregningskoderSykepengegrunnlag {
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_SKJOENN_AVVIK,
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_SKJOENN_URIKTIG,
    FRILANSER_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    FRILANSER_SYKEPENGEGRUNNLAG_SKJOENN_AVVIK,
    FRILANSER_SYKEPENGEGRUNNLAG_SKJOENN_URIKTIG,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_SKJOENN_VARIG_ENDRING,
    SELVSTENDIG_SYKEPENGEGRUNNLAG_SKJOENN_NYIARB,
    INAKTIV_SYKEPENGEGRUNNLAG_HOVEDREGEL,
    INAKTIV_SYKEPENGEGRUNNLAG_SKJOENN_VARIG_ENDRING,
    INAKTIV_SYKEPENGEGRUNNLAG_SKJOENN_NYIARB,
    ARBEIDSLEDIG_SYKEPENGEGRUNNLAG_DAGPENGER,
    ARBEIDSLEDIG_SYKEPENGEGRUNNLAG_VENTELOENN,
    ARBEIDSLEDIG_SYKEPENGEGRUNNLAG_VARTPENGER,
    ARBEIDSTAKER_SYKEPENGEGRUNNLAG_TIDSBEGRENSET_FOER_SLUTTDATO,
}

enum class BeregningskoderKombinasjonerSykepengegrunnlag {
    KOMBINERT_ARBEIDSTAKER_SELVSTENDIG_SYKEPENGEGRUNNLAG,
    KOMBINERT_ARBEIDSTAKER_FRILANSER_SYKEPENGEGRUNNLAG,
    KOMBINERT_FRILANSER_SELVSTENDIG_SYKEPENGEGRUNNLAG,
    KOMBINERT_ARBEIDSTAKER_FRILANSER_SELVSTENDIG_SYKEPENGEGRUNNLAG,
}
