apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: speilvendt
  name: bakrommet
  namespace: speilvendt
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
    disableAutoScaling: true
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: '4373da97-ad06-40c0-893e-98ba4d0aeecb' # helse-spillerom-saksbehandler
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-f1-micro
        databases:
          - name: bakrommet
            envVarPrefix: DATABASE
  accessPolicy:
    inbound:
      rules:
        - application: spillerom
    outbound:
      rules:
          - application: sykepengesoknad-backend
            namespace: flex
          - application: logging
            namespace: nais-system
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: aareg-services.dev-fss-pub.nais.io
  env:
    - name: PDL_SCOPE
      value: dev-fss.pdl.pdl-api
    - name: PDL_HOSTNAME
      value: pdl-api.dev-fss-pub.nais.io
    - name: SYKEPENGESOKNAD_BACKEND_SCOPE
      value: dev-gcp.flex.sykepengesoknad-backend
    - name: SYKEPENGESOKNAD_BACKEND_HOSTNAME
      value: http://sykepengesoknad-backend.flex
    - name: AAREG_HOSTNAME
      value: aareg-services.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: dev-fss.arbeidsforhold.aareg-services-nais
    - name: INNTEKTSKOMPONENTEN_HOSTNAME
      value: ikomp-q2.dev-fss-pub.nais.io
    - name: INNTEKTSKOMPONENTEN_SCOPE
      value: dev-fss.team-inntekt.ikomp-q2
