apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: speilvendt
  name: bakrommet
  namespace: speilvendt
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
    disableAutoScaling: true
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: '4373da97-ad06-40c0-893e-98ba4d0aeecb' # helse-spillerom-saksbehandler
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-f1-micro
        databases:
          - name: bakrommet
            envVarPrefix: DATABASE
  accessPolicy:
    inbound:
      rules:
        - application: spillerom