dependencies {
    api(platform(project(":bakrommet-dependencies")))

    implementation("com.zaxxer:HikariCP")

    testImplementation(project(":bakrommet-bootstrap"))
    testImplementation(project(":bakrommet-services"))
    testImplementation(project(":bakrommet-common"))
    testImplementation(project(":bakrommet-api-dto"))
    testImplementation(project(":bakrommet-api"))
    testImplementation(project(":bakrommet-client-aareg"))
    testImplementation(project(":bakrommet-client-ainntekt"))
    testImplementation(project(":bakrommet-client-ereg"))
    testImplementation(project(":bakrommet-client-pdl"))
    testImplementation(project(":bakrommet-client-sigrun"))
    testImplementation(project(":bakrommet-client-inntektsmelding"))
    testImplementation(project(":bakrommet-client-sykepengesoknad"))
    testImplementation(project(":sykepenger-model"))

    testImplementation("com.github.seratch:kotliquery")

    testImplementation("io.ktor:ktor-server-core")
    testImplementation("io.ktor:ktor-server-test-host")
    testImplementation("io.ktor:ktor-client-core")
    testImplementation("io.ktor:ktor-client-content-negotiation")
    testImplementation("io.ktor:ktor-client-mock-jvm")
    testImplementation("io.ktor:ktor-serialization-jackson")
    testImplementation("io.ktor:ktor-client-apache-jvm")
    testImplementation("io.ktor:ktor-server-auth-jwt")

    testImplementation("org.testcontainers:postgresql")
    testImplementation("no.nav.security:mock-oauth2-server")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    testImplementation("no.nav.helse.flex:sykepengesoknad-kafka")
    testImplementation("com.github.navikt.spleis:sykepenger-okonomi")

    testImplementation(testFixtures(project(":bakrommet-services")))
    testImplementation(testFixtures(project(":bakrommet-common")))
    testImplementation(testFixtures(project(":bakrommet-client-inntektsmelding")))
    testImplementation(testFixtures(project(":bakrommet-client-ainntekt")))
    testImplementation(testFixtures(project(":bakrommet-client-aareg")))
    testImplementation(testFixtures(project(":bakrommet-client-ereg")))
    testImplementation(testFixtures(project(":bakrommet-client-sigrun")))
    testImplementation(testFixtures(project(":bakrommet-client-sykepengesoknad")))
    testImplementation(testFixtures(project(":bakrommet-client-pdl")))
}
