@startuml

class Behandling

class Sykefraværstilfelle

class Sykepengegrunnlag

class Beregning

interface Yrkesaktivitetsperiode

class Yrkesaktivitet

class Inntektsgrunnlag

class MedSykdom as "Periode med sykdom"

class UtenSykdom as "Periode uten sykdom"

class VurdertVilkår as "Vurdert vilkår"

Behandling --> Yrkesaktivitetsperiode: omfatter en eller flere
Behandling --> Sykefraværstilfelle: inngår i et
Sykefraværstilfelle --> Yrkesaktivitet: har en eller flere \n på skjæringstidspunktet
Sykefraværstilfelle --> Sykepengegrunnlag: har 0 eller ett
Sykepengegrunnlag --> Inntektsgrunnlag: består av 0, en eller flere
Yrkesaktivitet --> Inntektsgrunnlag: har 0 eller en

Behandling <-- VurdertVilkår: tilhører en
Yrkesaktivitetsperiode --> Yrkesaktivitet: tilhører én
MedSykdom --|> Yrkesaktivitetsperiode: er en
UtenSykdom --|> Yrkesaktivitetsperiode: er en
Behandling --> Beregning: har kanskje en

note top of UtenSykdom
  Skille på ghost og tilkommen inntekt?
end note

hide empty members
hide circle

@enduml
