package no.nav.helse.bakrommet.api.dto.utbetalingsberegning

enum class BeregningskoderDekningsgradDto {
    ARBEIDSTAKER_DEKNINGSGRAD_100,
    SELVSTENDIG_DEKNINGSGRAD_80,
    SELVSTENDIG_NAVFORSIKRING_DEKNINGSGRAD_80,
    SELVSTENDIG_NAVFORSIKRING_DEKNINGSGRAD_100,
    SELVSTENDIG_KOLLEKTIVFORSIKRING_DEKNINGSGRAD_100,
    FRILANSER_DEKNINGSGRAD_100,
    INAKTIV_DEKNINGSGRAD_65,
    INAKTIV_DEKNINGSGRAD_100,
    ARBEIDSLEDIG_DEKNINGSGRAD_100,
}
